
const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=56',
  'https://sanand0.github.io/tdsdata/js_table/?seed=57',
  'https://sanand0.github.io/tdsdata/js_table/?seed=58',
  'https://sanand0.github.io/tdsdata/js_table/?seed=59',
  'https://sanand0.github.io/tdsdata/js_table/?seed=60',
  'https://sanand0.github.io/tdsdata/js_table/?seed=61',
  'https://sanand0.github.io/tdsdata/js_table/?seed=62',
  'https://sanand0.github.io/tdsdata/js_table/?seed=63',
  'https://sanand0.github.io/tdsdata/js_table/?seed=64',
  'https://sanand0.github.io/tdsdata/js_table/?seed=65',
];

(async () => {
  // Launch an invisible browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    // Go to the page
    await page.goto(url);

    // Wait for the table to load (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all table cell text values
    const numbers = await page.$$eval('td', cells =>
      cells
        .map(cell => parseFloat(cell.innerText))  // Convert text to number
        .filter(n => !isNaN(n))                   // Keep only actual numbers
    );

    const pageSum = numbers.reduce((a, b) => a + b, 0);
    console.log(`Seed ${url.split('seed=')[1]}: sum = ${pageSum}`);
    grandTotal += pageSum;
  }

  await browser.close();

  // This is what the grader will look for in the logs
  console.log(`Total sum across all pages: ${grandTotal}`);
})();
