const { chromium } = require('playwright');

const urls = [
  'https://sanand0.github.io/tdsdata/js_table/?seed=56',
  'https://sanand0.github.io/tdsdata/js_table/?seed=57',
  'https://sanand0.github.io/tdsdata/js_table/?seed=58',
  'https://sanand0.github.io/tdsdata/js_table/?seed=59',
  'https://sanand0.github.io/tdsdata/js_table/?seed=60',
  'https://sanand0.github.io/tdsdata/js_table/?seed=61',
  'https://sanand0.github.io/tdsdata/js_table/?seed=62',
  'https://sanand0.github.io/tdsdata/js_table/?seed=63',
  'https://sanand0.github.io/tdsdata/js_table/?seed=64',
  'https://sanand0.github.io/tdsdata/js_table/?seed=65',
];

(async () => {
  // Launch an invisible browser
  const browser = await chromium.launch();
  const page = await browser.newPage();

  let grandTotal = 0;

  for (const url of urls) {
    // Go to the page
    await page.goto(url);

    // Wait for the table to load (it's dynamically generated by JavaScript)
    await page.waitForSelector('table');

    // Grab all table cell text values
    const numbers = await page.$$eval('td', cells =>
      cells
        .map(cell => parseFloat(cell.innerText))  // Convert text to number
        .filter(n => !isNaN(n))                   // Keep only actual numbers
    );

    const pageSum = numbers.reduce((a, b) => a + b, 0);
    console.log(`Seed ${url.split('seed=')[1]}: sum = ${pageSum}`);
    grandTotal += pageSum;
  }

  await browser.close();

  // This is what the grader will look for in the logs
  console.log(`Total sum across all pages: ${grandTotal}`);
})();
```

**What this script does, simply:**
- Opens a hidden Chrome browser (Playwright controls it like a robot)
- Visits each of the 10 URLs one by one
- Waits for the table to appear (these pages load data with JavaScript, so we must wait)
- Reads every cell, converts text to numbers, ignores non-numbers
- Adds them all up and prints the grand total

---

## Step 5: Commit Both Files

After creating each file, scroll down and click **Commit new file** (green button).

Once both files are committed, the Action will **automatically trigger** because you pushed to `main`.

---

## Step 6: Watch Your Action Run

1. Go to your repo on GitHub
2. Click the **Actions** tab (top menu)
3. You'll see a workflow run in progress (yellow circle = running, green = done)
4. Click on it → click on the **scrape** job → click the step with your email
5. You'll see the printed sums in the logs!

---

## Step 7: Create a Personal Access Token (PAT)

The assignment asks for your repo URL + a GitHub token. Here's how to get the token:

1. Go to GitHub → click your profile photo (top right) → **Settings**
2. Scroll down to **Developer settings** (bottom of left sidebar)
3. Click **Personal access tokens → Tokens (classic)**
4. Click **Generate new token (classic)**
5. Give it a name like `assignment-token`
6. Set expiration to 7 days (enough for grading)
7. Check these scopes:
   - ✅ `repo` (full repo access)
   - ✅ `workflow` (needed to read action logs)
8. Click **Generate token**
9. **Copy it immediately** — GitHub won't show it again!

---

## Step 8: Submit Your Answer

Your answer should look like:
```
https://github.com/YOUR_USERNAME/playwright-scraper ghp_xxxxxxxxxxxxxxxxxxxx
